backend:
    name: git-gateway
    branch: main
media_folder: "images"
collections:
    - name: "posts"
      label: "Posts"
      folder: "posts"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "Body", name: "body", widget: "code" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
